version: '2'
networks:
    dockernet:
        external: true
services:
    owncloud:
      image: havonte/owncloud-single
      hostname: $DYNDNS_TLD
      networks:
       - dockernet
      ports:
       - 443:443
      volumes:
       - $HOST_DIR:$CONTAINER_DIR

