version: '2'
networks:
    ownnet:
      driver: bridge  
services:
    mariadb:
      image: lsioarmhf/mariadb
      ports:
       - 3306
      environment:
       - PUID=33 
       - PGID=33 
       - MYSQL_ROOT_PASSWORD=admin
       - TZ=Europe/Berlin 
      networks:
       - ownnet
    owncloud:
      image: havonte/owncloud-single
      hostname: $DYNDNS_TLD
      networks:
       - ownnet
      ports:
       - 443:443
      depends_on:
       - mariadb
      environment:
       - SUBJECT=/C=DE/ST=B/L=CITY/O=§yourname/OU=UNIT/CN=$DYNDNS_TLD
       - TARGET_SUBDIR=/
       - VIRTUAL_HOST=$DYNDNS_TLD
      volumes:
       - $hostOcpath/data:/usr/share/webapps/owncloud/data
       - $hostOcpath/config:/usr/share/webapps/owncloud/config
       - $hostOcpath/apps:/usr/share/webapps/owncloud/apps

