version: '2'
networks:
    ownnet:
      driver: bridge  
services:
    postgres:
      image: encodeering/postgres-armhf:9.4
      ports:
       - 5432
      environment:
       - POSTGRES_PASSWORD=admin 
      networks:
       - ownnet
    owncloud:
      image: havonte/owncloud-single
      hostname: $DYNDNS_TLD
      networks:
       - ownnet
      ports:
       - 443:443
      depends_on:
       - postgres
      volumes:
       - $HOST_DIR:$CONTAINER_DIR

