version: '2'
networks:
    dockernet:
        external: true
services:
    owncloud:
      image: havonte/owncloud-single
      hostname: $DYNDNS_TLD
      networks:
       - ownnet
      ports:
       - 443:443
      environment:
       - SUBJECT=/C=DE/ST=B/L=CITY/O=§yourname/OU=UNIT/CN=$DYNDNS_TLD
       - TARGET_SUBDIR=/
       - VIRTUAL_HOST=$DYNDNS_TLD
      volumes:
       - $hostOcpath/data:/usr/share/webapps/owncloud/data
       - $hostOcpath/config:/usr/share/webapps/owncloud/config
       - $hostOcpath/apps:/usr/share/webapps/owncloud/apps


