version: '2'
networks:
    ownnet:
      driver: bridge  
services:
    mariadb:
      image: lsioarmhf/mariadb
      ports:
       - 3306
      environment:
       - PUID=33 
       - PGID=33 
       - MYSQL_ROOT_PASSWORD=admin
       - TZ=Europe/Berlin 
      networks:
       - ownnet
    owncloud:
      image: havonte/owncloud-single
      hostname: $DYNDNS_TLD
      networks:
       - ownnet
      ports:
       - 443:443
      depends_on:
       - mariadb
      volumes:
       - $HOST_DIR:$CONTAINER_DIR

